BoxLayout:
    orientation: "vertical"

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 0.1

        Button:
            text: "List"
        Button:
            text: "0"
        Button:
            text: "0"
        Button:
            text: "Submit"

    Carousel:
        size_hint_y: 0.9

        GridLayout:
            id: price_keypad
            cols: 4
        GridLayout:
            id: products_keypad
            cols: 2
